In [1]:
import numpy as np
import pandas as pd
import string
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import wordnet
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix

data = pd.read_csv('spam.csv')


def remove_punctuation(text):
    punctuationfree = "".join([i for i in text if i not in string.punctuation])
    return punctuationfree


data['Message'] = data['Message'].apply(lambda x: remove_punctuation(x))

data['Message'] = data['Message'].apply(lambda x: x.lower())

data['Message'] = data['Message'].apply(lambda x: re.split(r"\s+", x))

stopwords = nltk.corpus.stopwords.words('english')


def remove_stopwords(text):
    output = [i for i in text if i not in stopwords]
    return output


data['Message'] = data['Message'].apply(lambda x: remove_stopwords(x))

lemm = nltk.stem.WordNetLemmatizer()

data['Message'] = data['Message'].apply(lambda x: [lemm.lemmatize(word) for word in x])
data

Category                                            Message
0         ham  [go, jurong, point, crazy, available, bugis, n...
1         ham                     [ok, lar, joking, wif, u, oni]
2        spam  [free, entry, 2, wkly, comp, win, fa, cup, fin...
3         ham      [u, dun, say, early, hor, u, c, already, say]
4         ham  [nah, dont, think, go, usf, life, around, though]
...       ...                                                ...
5567     spam  [2nd, time, tried, 2, contact, u, u, £750, pou...
5568      ham                 [ü, b, going, esplanade, fr, home]
5569      ham                    [pity, mood, soany, suggestion]
5570      ham  [guy, bitching, acted, like, id, interested, b...
5571      ham                                 [rofl, true, name]

[5572 rows x 2 columns]

In [2]:
data['Message_String'] = data['Message'].apply(lambda x: ' '.join([item for item in x]))
data['Category'] = data['Category'].replace({'ham':0,'spam':1})
data.head()

Category                                            Message  \
0         0  [go, jurong, point, crazy, available, bugis, n...   
1         0                     [ok, lar, joking, wif, u, oni]   
2         1  [free, entry, 2, wkly, comp, win, fa, cup, fin...   
3         0      [u, dun, say, early, hor, u, c, already, say]   
4         0  [nah, dont, think, go, usf, life, around, though]   

                                      Message_String  
0  go jurong point crazy available bugis n great ...  
1                            ok lar joking wif u oni  
2  free entry 2 wkly comp win fa cup final tkts 2...  
3                u dun say early hor u c already say  
4           nah dont think go usf life around though

In [3]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()
transformed = ohe.fit_transform(data[['Message_String']])
print(transformed.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [4]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix
from sklearn.model_selection import cross_val_score, cross_val_predict

lr = LogisticRegression(random_state=1)
y = data['Category']
x_vect = transformed

vectorizer_score = cross_val_score(lr, x_vect, y, cv=3)
vectorizer_score.mean()


0.8659368183575603